server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///security_authority?useSSL=false
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
## actuator
management:
  endpoints:
    web.exposure.include: "*"

mybatis:
  type-aliases-package: me.itwl.authservice.domain
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    me.itwl.authservice: debug

